### ISSUE TITLE
Docker Compose bitcoin rpc node issue

### ISSUE THREAD

**Issue by yallxe** [vulpemventures/nigiri#124]
Installing nigiri, there is an issue while creating `docker-compose.yml` in `~/.nigiri/`.
```yaml
services:
  # RPC daemon
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin:latest
    container_name: bitcoin
    command:
      - -datadir=config
    ports:
      - 18443:18433
      - 18444:18444
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped
```

JSON-RPC bitcoin node ports are defined incorrectly, instead of `- 18443:18433` it has to be `- 18443:18443` for working properly. I don't know golang at all so i can't do a pull request.
